apiVersion: v1
kind: PersistentVolume
metadata:
  name: voting-postgres-pv
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: example-voting-app
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: voting-postgres-manual
  hostPath:
    path: /data/voting-postgres
    type: DirectoryOrCreate
