apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: voting-app
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: example-voting-app
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: voting-postgres-manual
  volumeName: voting-postgres-pv
  resources:
    requests:
      storage: 1Gi
